all: pacman

pacman: pacman.o renderer.o font.o bitmaps.o model.o events.o raster.o rast_asm.o psg.o music.o effects.o isr.o isr_asm.o globals.o input.o win_scr.o lose_scr.o splash.o                             
	cc68x -g pacman.o renderer.o font.o bitmaps.o model.o events.o raster.o rast_asm.o psg.o music.o effects.o isr.o isr_asm.o globals.o input.o win_scr.o lose_scr.o splash.o -o pacman

pacman.o: pacman.c pacman.h raster.h font.h bitmaps.h model.h events.h renderer.h isr.h globals.h input.h win_scr.h lose_scr.h splash.h
	cc68x -g -c pacman.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

events.o: events.c events.h
	cc68x -g -c events.c

font.o: font.c font.h
	cc68x -g -c font.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

model.o: model.c model.h bitmaps.h events.h
	cc68x -g -c model.c

renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

psg.o: psg.c psg.h
	cc68x -g -c psg.c

music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

globals.o: globals.c globals.h
	cc68x -g -c globals.c

isr_asm.o: isr_asm.s
	gen -D -L2 isr_asm.s

isr.o: isr.c isr.h music.h effects.h pacman.h input.h 
	cc68x -g -c isr.c

input.o: input.c input.h 
	cc68x -g -c input.c

win_scr.o: win_scr.c win_scr.h
	cc68x -g -c win_scr.c

lose_scr.o: lose_scr.c lose_scr.h
	cc68x -g -c lose_scr.c

splash.o: splash.c splash.h
	cc68x -g -c splash.c
	


#all: tst_snd
#
#tst_snd: tst_snd.o psg.o music.o effects.o
#	cc68x -g tst_snd.o psg.o music.o effects.o -o tst_snd
#
#tst_snd.o: tst_snd.c psg.h TYPES.H music.h effects.h
#	cc68x -g -c tst_snd.c
#
#psg.o: psg.c psg.h
#	cc68x -g -c psg.c
#
#music.o: music.c music.h
#	cc68x -g -c music.c
#
#effects.o: effects.c effects.h
#	cc68x -g -c effects.c
