

all: pacman

pacman: pacman.o renderer.o font.o bitmaps.o model.o events.o raster.o rast_asm.o
	cc68x -g pacman.o renderer.o font.o bitmaps.o model.o events.o raster.o rast_asm.o -o pacman

pacman.o: pacman.c pacman.h raster.h font.h bitmaps.h model.h events.h renderer.h
	cc68x -g -c pacman.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

events.o: events.c events.h
	cc68x -g -c events.c

font.o: font.c font.h
	cc68x -g -c font.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

model.o: model.c model.h bitmaps.h events.h
	cc68x -g -c model.c

renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

# all: tst_struct tst_rend tst_rast tst_pac

# tst_struct: tst_strc.o font.o bitmaps.o model.o events.o rast_asm.o
# 	cc68x -g tst_strc.o raster.o font.o bitmaps.o model.o events.o rast_asm.o -o tst_struct

# tst_strc.o: tst_strc.c raster.o font.h bitmaps.h model.h events.h
# 	cc68x -g -c tst_strc.c

# tst_rend: tst_rend.o renderer.o raster.o font.o bitmaps.o model.o events.o rast_asm.o
# 	cc68x -g tst_rend.o renderer.o raster.o font.o bitmaps.o model.o events.o rast_asm.o -o tst_rend	

# tst_rend.o: tst_rend.c raster.h font.h bitmaps.h model.h renderer.h events.h
# 	cc68x -g -c tst_rend.c

# tst_rast: tst_rast.o raster.o font.o bitmaps.o rast_asm.o
# 	cc68x -g tst_rast.o raster.o font.o bitmaps.o rast_asm.o -o tst_rast

# tst_rast.o: tst_rast.c raster.h font.h bitmaps.h
# 	cc68x -g -c tst_rast.c

# raster.o: raster.c raster.h
# 	cc68x -g -c raster.c

# events.o: events.c events.h
# 	cc68x -g -c events.c

# font.o: font.c font.h
# 	cc68x -g -c font.c

# bitmaps.o: bitmaps.c bitmaps.h
# 	cc68x -g -c bitmaps.c

# model.o: model.c model.h bitmaps.h events.h
# 	cc68x -g -c model.c

# renderer.o: renderer.c renderer.h
# 	cc68x -g -c renderer.c

# rast_asm.o: rast_asm.s
# 	gen -D -L2 rast_asm.s


#### 

# tst_struct: tst_strc.o structs.o font.o bitmaps.o model.o events.o rast_asm.o
# 	cc68x -g tst_strc.o structs.o font.o bitmaps.o model.o events.o rast_asm.o -o tst_struct

# tst_strc.o: tst_strc.c struct.h font.h bitmaps.h model.h events.h
# 	cc68x -g -c tst_strc.c

# structs.o: structs.c struct.h 
# 	cc68x -g -c structs.c

# events.o: events.c events.h
# 	cc68x -g -c events.c

# font.o: font.c font.h
# 	cc68x -g -c font.c

# bitmaps.o: bitmaps.c bitmaps.h
# 	cc68x -g -c bitmaps.c

# model.o: model.c model.h bitmaps.h events.h
# 	cc68x -g -c model.c

# rast_asm.o: rast_asm.s
# 	gen -D -L2 rast_asm.s

