
tst_struct: tst_strc.o structs.o font.o bitmaps.o rast_asm.o
	cc68x -g tst_strc.o structs.o font.o bitmaps.o rast_asm.o -o tst_struct

tst_strc.o: tst_strc.c struct.h font.h bitmaps.h model.h 
	cc68x -g -c tst_strc.c

structs.o: structs.c struct.h 
	cc68x -g -c structs.c

font.o: font.c font.h
	cc68x -g -c font.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	
#tst_rast: tst_strc.o structs.o font.o bitmaps.o
#	cc68x -g tst_strc.o structs.o font.o bitmaps.o -o tst_rast
#
#tst_strc.o: tst_strc.c struct.h font.h bitmaps.h
#	cc68x -g -c tst_strc.c
#
#structs.o: structs.c struct.h
#	cc68x -g -c structs.c
#
#font.o: font.c font.h
#	cc68x -g -c font.c
#
#bitmaps.o: bitmaps.c bitmaps.h
#	cc68x -g -c bitmaps.c
#


	

# original makefile
#tst_rast: tst_strc.o structs.o rast_asm.o
#	cc68x -g tst_strc.o structs.o rast_asm.o -o tst_rast

#tst_strc.o: tst_strc.c struct.h
#	cc68x -g -c tst_strc.c

#structs.o: structs.c struct.h
#	cc68x -g -c structs.c

#rast_asm.o: rast_asm.s
#	gen -D -L2 rast_asm.s

#clean:
#	rm -f *.o 

