
tst_rast: tst_rast.o raster.o font.o bitmaps.o rast_asm.o
	cc68x -g tst_rast.o raster.o font.o bitmaps.o rast_asm.o -o tst_rast

tst_rast.o: tst_rast.c raster.h font.h bitmaps.h model.h input.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h model.h input.h
	cc68x -g -c raster.c

font.o: font.c font.h
	cc68x -g -c font.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
	
#tst_rast: tst_rast.o raster.o font.o bitmaps.o
#	cc68x -g tst_rast.o raster.o font.o bitmaps.o -o tst_rast
#
#tst_rast.o: tst_rast.c raster.h font.h bitmaps.h
#	cc68x -g -c tst_rast.c
#
#raster.o: raster.c raster.h
#	cc68x -g -c raster.c
#
#font.o: font.c font.h
#	cc68x -g -c font.c
#
#bitmaps.o: bitmaps.c bitmaps.h
#	cc68x -g -c bitmaps.c
#


	

# original makefile
#tst_rast: tst_rast.o raster.o rast_asm.o
#	cc68x -g tst_rast.o raster.o rast_asm.o -o tst_rast

#tst_rast.o: tst_rast.c raster.h
#	cc68x -g -c tst_rast.c

#raster.o: raster.c raster.h
#	cc68x -g -c raster.c

#rast_asm.o: rast_asm.s
#	gen -D -L2 rast_asm.s

#clean:
#	rm -f *.o 

